version: '3'
    
services:

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env/development/database
      - .env/development/web

  redis:
     image: redis

  database:
    image: postgres:9.6
    env_file:
      - .env/development/database

volumes:
  gem_cache: